version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.62
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.12
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.16
    - 1.17.17
    - 1.17.19
    - 1.17.20
    - 1.17.21
    - 1.17.23
    - 1.17.24
    - 1.17.26
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.31
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.37
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.42
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.59
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: zope-interface
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: prompt-toolkit
    versions:
    - 3.0.14
    - 3.0.15
    - 3.0.16
    - 3.0.17
  - dependency-name: qtconsole
    versions:
    - 5.0.2
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: jupyter-core
    versions:
    - 4.7.0
  - dependency-name: pyyaml
    versions:
    - "5.1"
  - dependency-name: bleach
    versions:
    - 3.1.4
